In [4]:
import pandas as pd 
from pathlib import Path

In [5]:
data_folder = Path(".")
departments_path = data_folder / "departments.csv"
departments=pd.read_csv(departments_path)

In [6]:
departments=pd.read_csv(departments_path)

In [7]:
departments.shape

(20, 3)

In [8]:
departments.head()

   department_id department_name   location
0              1    Department_1     Mumbai
1              2    Department_2  Hyderabad
2              3    Department_3       Pune
3              4    Department_4       Pune
4              5    Department_5     Mumbai

In [10]:
departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    20 non-null     int64
 1   department_name  20 non-null     object
 2   location         20 non-null     object
dtypes: int64(1), object(2)
memory usage: 608.0+ bytes

In [12]:
departments.describe()

       department_id
count       20.00000
mean        10.50000
std          5.91608
min          1.00000
25%          5.75000
50%         10.50000
75%         15.25000
max         20.00000

In [13]:
departments.isnull().sum()

department_id      0
department_name    0
location           0
dtype: int64

In [14]:
departments.duplicated().sum()

0

In [15]:
departments.to_csv("departments-cleaned.csv",index=False)